name: CI Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run linting with flake8
              run: |
                flake8 .

            - name: Run tests with pytest
              run: |
                pytest tests/test_sentiment.py

            - name: Build Docker Image
              run: |
                docker build -t sentiment-analyzer .
